### ISSUE TITLE
About docker enviroment issue (Import error)

### ISSUE THREAD

**Issue by Choi-YeongJoon** [hirotomusiker/CLRerNet#27]
I have been using clrnet to detect lanes, but It didn't recognize the curve very well.
So, I felt the need to try the clrernet you suggested.

Docker was built successfully, but inference was not possible due to the following error:

/home/docker/.pyenv/versions/3.8.4/lib/python3.8/site-packages/torch/cuda/__init__.py:83: UserWarning: CUDA initialization: Unexpected error from cudaGetDeviceCount(). Did you run some cuda functions before calling NumCudaDevices() that might have already set an error? Error 804: forward compatibility was attempted on non supported HW (Triggered internally at  ../c10/cuda/CUDAFunctions.cpp:109.)
  return torch._C._cuda_getDeviceCount() > 0
No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
/home/docker/.pyenv/versions/3.8.4/lib/python3.8/site-packages/mmcv/__init__.py:20: UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components related to the training process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.
  warnings.warn(
Traceback (most recent call last):
  File "/home/docker/.pyenv/versions/3.8.4/lib/python3.8/site-packages/mmcv/utils/misc.py", line 73, in import_modules_from_strings
    imported_tmp = import_module(imp)
  File "/home/docker/.pyenv/versions/3.8.4/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/work/libs/models/__init__.py", line 2, in <module>
    from .dense_heads import CLRerHead  # noqa: F401
  File "/work/libs/models/dense_heads/__init__.py", line 1, in <module>
    from .clrernet_head import CLRerHead  # noqa: F401
  File "/work/libs/models/dense_heads/clrernet_head.py", line 13, in <module>
    from nms import nms
  File "/home/docker/.pyenv/versions/3.8.4/lib/python3.8/site-packages/nms-0.0.0-py3.8-linux-x86_64.egg/nms/__init__.py", line 29, in <module>
    from . import details
ImportError: /home/docker/.pyenv/versions/3.8.4/lib/python3.8/site-packages/nms-0.0.0-py3.8-linux-x86_64.egg/nms/details.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZNK3c107SymBool10guard_boolEPKcl

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "demo/image_demo.py", line 36, in <module>
    main(args)
  File "demo/image_demo.py", line 27, in main
    model = init_detector(args.config, args.checkpoint, device=args.device)
  File "/home/docker/mmdetection/mmdet/apis/inference.py", line 33, in init_detector
    config = mmcv.Config.fromfile(config)
  File "/home/docker/.pyenv/versions/3.8.4/lib/python3.8/site-packages/mmcv/utils/config.py", line 343, in fromfile
    import_modules_from_strings(**cfg_dict['custom_imports'])
  File "/home/docker/.pyenv/versions/3.8.4/lib/python3.8/site-packages/mmcv/utils/misc.py", line 80, in import_modules_from_strings
    raise ImportError
ImportError

Regarding the error, I referred to issue #4 but it didn't solve it! (My gpu version is 1080ti, so I build options applied --build-arg TORCH_CUDA_ARCH_LIST="6.1")

In my docker container, torch version is 1.12.1+cu116. but, cuda version is 11.8. (nvcc -V)
Is it right? 

And torch.cuda.is_available() return False. 

I changed the torch version, but couldn't solve it.

Help me, please...

**Comment by hirotomusiker** [comment]
Thank you.
First, does `nvidia-smi` work in your container?
Second, can you install `nms` in your container? [[tips](https://github.com/hirotomusiker/CLRerNet/blob/main/docs/INSTALL.md)]
```
cd libs/models/layers/nms/
python setup.py install
cd /work
```

**Comment by confusedgreenhand** [comment]
> Thank you. First, does `nvidia-smi` work in your container? Second, can you install `nms` in your container? [[tips](https://github.com/hirotomusiker/CLRerNet/blob/main/docs/INSTALL.md)]
> 
> ```
> cd libs/models/layers/nms/
> python setup.py install
> cd /work
> ```


hi, i met the same problem when i run the demo
![clrernet_demo_error](https://github.com/hirotomusiker/CLRerNet/assets/49227338/3154d3d0-f0f0-4751-ab4d-f82c60601ce6)

1) nvidia-smi work in my container
2) but i can not install nms in my container, and i tried to add "--build-arg TORCH_CUDA_ARCH_LIST="7.5;8.0;8.6"", nms failed install either
![nms_install_error](https://github.com/hirotomusiker/CLRerNet/assets/49227338/f7d4fec7-f78b-4746-bfce-a106f617cc34)
3) torch.cuda.is_available() return False  in my container

could you give me any advice? thanks a lot.

**Comment by hirotomusiker** [comment]
The error seems to be due to installation failure of torch. 
Please check if torch is correctly in the container and `torch.cuda.is_available()` returns `True`, otherwise `nms` won't be installed.
