### ISSUE TITLE
KeyError: 'CLRerNet: "CLRerHead: \'DynamicTopkAssigner is not in the bbox_assigner registry\'"'

### ISSUE THREAD

**Issue by mihirkalakamb029** [hirotomusiker/CLRerNet#32]
Hello, 

I'm trying to regenerate your results, but I'm getting a KeyError while validating the model. It would be appreciable if you could help me debug this error.

Note: I followed the steps and solution provided in the #6 earlier.

Traceback (most recent call last):
  File "tools/test.py", line 264, in <module>
    main()
  File "tools/test.py", line 208, in main
    model = build_detector(cfg.model, test_cfg=cfg.get('test_cfg'))
  File "/home/sandlogic/anaconda3/envs/clrernet/lib/python3.8/site-packages/mmdet/models/builder.py", line 58, in build_detector
    return DETECTORS.build(
  File "/home/sandlogic/anaconda3/envs/clrernet/lib/python3.8/site-packages/mmcv/utils/registry.py", line 237, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/home/sandlogic/anaconda3/envs/clrernet/lib/python3.8/site-packages/mmcv/cnn/builder.py", line 27, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/home/sandlogic/anaconda3/envs/clrernet/lib/python3.8/site-packages/mmcv/utils/registry.py", line 72, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
KeyError: 'CLRerNet: "CLRerHead: \'DynamicTopkAssigner is not in the bbox_assigner registry\'"'

**Comment by hirotomusiker** [comment]
Thank you.
`DynamicTopkAssigner` is imported via `custom_import` in your config file.
https://github.com/hirotomusiker/CLRerNet/blob/main/configs/clrernet/culane/clrernet_culane_dla34.py#L8-L17
Could you provide the command including the config file you used?

**Comment by mihirkalakamb029** [comment]
Thank you for the reply. I could resolve the issue. 
The command I had used was: `python3 tools/test.py configs/clrernet/culane/clrernet_culane_dla34_ema.py clrernet_culane_dla34_ema.pth` and the issue was with the config file. `libs.core.bbox` and `libs.core.hook` are missing in [https://github.com/hirotomusiker/CLRerNet/blob/main/configs/clrernet/culane/clrernet_culane_dla34_ema.py].

**Comment by hirotomusiker** [comment]
Thank you, it should be corrected. We will add `libs.core.bbox` and `libs.core.hook` to `clrernet_culane_dla34_ema.py` in the next update 😄
