### ISSUE TITLE
Wrong Demo Result

### ISSUE THREAD

**Issue by StepTurtle** [hirotomusiker/CLRerNet#34]
Hi, great work.

I have a simple question with the demo code. When I run the demo.py with my image, the result looks like not fit on image. I just changed crop_bbox parameter from [config](https://github.com/hirotomusiker/CLRerNet/blob/main/configs/clrernet/culane/dataset_culane_clrernet.py) and I connot find any other parameter for this

Terminal command I used:
`python demo/image_demo.py demo/image_910.jpg configs/clrernet/culane/clrernet_culane_dla34_ema.py clrernet_culane_dla34_ema.pth --out-file=result.png`

Parameter which I changed:
`crop_bbox = [0, 0, 1640, 590]`

![result](https://github.com/hirotomusiker/CLRerNet/assets/76053179/b4ed43b8-fb58-4cfe-ad6f-ea1e2ffc134f)

Also I got different error when I changed `img_scale`:

```
/home/docker/.pyenv/versions/3.8.4/lib/python3.8/site-packages/mmcv/__init__.py:20: UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components related to the training process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.
  warnings.warn(
load checkpoint from local path: clrernet_culane_dla34_ema.pth
The model and loaded state dict do not match exactly

missing keys in source state_dict: bbox_head.loss_seg.criterion.weight, bbox_head.seg_decoder.conv.weight, bbox_head.seg_decoder.conv.bias

/home/docker/mmdetection/mmdet/apis/inference.py:51: UserWarning: Class names are not saved in the checkpoint's meta data, use COCO classes by default.
  warnings.warn('Class names are not saved in the checkpoint\'s '
Traceback (most recent call last):
  File "demo/image_demo.py", line 36, in <module>
    main(args)
  File "demo/image_demo.py", line 29, in main
    src, preds = inference_one_image(model, args.img)
  File "/work/libs/api/inference.py", line 53, in inference_one_image
    results = model(return_loss=False, rescale=True, **data)
  File "/home/docker/.pyenv/versions/3.8.4/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/docker/.pyenv/versions/3.8.4/lib/python3.8/site-packages/mmcv/runner/fp16_utils.py", line 119, in new_func
    return old_func(*args, **kwargs)
  File "/home/docker/mmdetection/mmdet/models/detectors/base.py", line 174, in forward
    return self.forward_test(img, img_metas, **kwargs)
  File "/work/libs/models/detectors/clrernet.py", line 55, in forward_test
    x = self.extract_feat(img)
  File "/home/docker/mmdetection/mmdet/models/detectors/single_stage.py", line 43, in extract_feat
    x = self.backbone(img)
  File "/home/docker/.pyenv/versions/3.8.4/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/work/libs/models/backbones/dla.py", line 427, in forward
    x = self.model(x)
  File "/home/docker/.pyenv/versions/3.8.4/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/work/libs/models/backbones/dla.py", line 385, in forward
    x = getattr(self, 'level{}'.format(i))(x)
  File "/home/docker/.pyenv/versions/3.8.4/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/work/libs/models/backbones/dla.py", line 265, in forward
    x1 = self.tree1(x, residual)
  File "/home/docker/.pyenv/versions/3.8.4/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/work/libs/models/backbones/dla.py", line 72, in forward
    out += residual
RuntimeError: The size of tensor a (117) must match the size of tensor b (116) at non-singleton dimension 2
```

**Comment by hirotomusiker** [comment]
Thank you.
Firstly, the following `test_cfg` parameters and the values of `crop_bbox` have to coincide.
https://github.com/hirotomusiker/CLRerNet/blob/main/configs/clrernet/base_clrernet.py#L76-L78
Specifically, you can change `cut_height=270,` to `cut_height=0,`.

Secondly, please make your width and height of `img_scale` divisible by 32 to avoid the RuntimeError. This occurs when the tensor 's spatial size changes through convolutions and does not match the size of the tensor that comes through skip connection.

**Comment by StepTurtle** [comment]
Everything look good now, thanks for clear and fast answer.
