### ISSUE TITLE
Inference issue

### ISSUE THREAD

**Issue by naren2cmu** [hirotomusiker/CLRerNet#35]
Has anyone tried to run the inference?

python demo/image_demo.py demo/demo.jpg configs/clrernet/culane/clrernet_culane_dla34_ema.py clrernet_culane_dla34_ema.pth --out-file=result.png

Several files necessary to run this seemed to be missing in the docker. And after I manually copied them, I am getting errors like below. 

```
docker@f1e69ee2c502:~/mmdetection$ python demo/image_demo.py demo/demo.jpg configs/clrernet/culane/clrernet_culane_dla34.py clrernet_culane_dla34.pth --out-file=result.png
/home/docker/.pyenv/versions/3.8.4/lib/python3.8/site-packages/mmcv/__init__.py:20: UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components related to the training process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.
  warnings.warn(
filename: clrernet_culane_dla34.pth
load checkpoint from local path: clrernet_culane_dla34.pth
CWD: /home/docker/mmdetection
Filename: clrernet_culane_dla34.pth
The model and loaded state dict do not match exactly

missing keys in source state_dict: bbox_head.loss_seg.criterion.weight, bbox_head.seg_decoder.conv.weight, bbox_head.seg_decoder.conv.bias

/home/docker/mmdetection/mmdet/apis/inference.py:51: UserWarning: Class names are not saved in the checkpoint's meta data, use COCO classes by default.
  warnings.warn('Class names are not saved in the checkpoint\'s '
Traceback (most recent call last):
  File "demo/image_demo.py", line 68, in <module>
    main(args)
  File "demo/image_demo.py", line 36, in main
    result = inference_detector(model, args.img)
  File "/home/docker/mmdetection/mmdet/apis/inference.py", line 127, in inference_detector
    test_pipeline = Compose(cfg.data.test.pipeline)
  File "/home/docker/mmdetection/mmdet/datasets/pipelines/compose.py", line 23, in __init__
    transform = build_from_cfg(transform, PIPELINES)
  File "/home/docker/.pyenv/versions/3.8.4/lib/python3.8/site-packages/mmcv/utils/registry.py", line 61, in build_from_cfg
    raise KeyError(
KeyError: 'albumentation is not in the pipeline registry'
```

**Comment by hirotomusiker** [comment]
Please run the command not in the `/home/docker/mmdetection/` folder, but the `/work/` folder.
Thank you.
