### ISSUE TITLE
TypeError: CLRerNet: __init__() missing 4 required positional arguments: 'code', 'msg', 'hdrs', and 'fp'

### ISSUE THREAD

**Issue by PangWeiye** [hirotomusiker/CLRerNet#43]
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Python\CLRerNet-main\image_demo.py", line 36, in <module>
    main(args)
  File "D:\Python\CLRerNet-main\image_demo.py", line 27, in main
    model = init_detector(args.config, args.checkpoint, device=args.device)
  File "C:\Annaconda\envs\SAM\lib\site-packages\mmdet\apis\inference.py", line 44, in init_detector
    model = build_detector(config.model, test_cfg=config.get('test_cfg'))
  File "C:\Annaconda\envs\SAM\lib\site-packages\mmdet\models\builder.py", line 58, in build_detector
    return DETECTORS.build(
  File "C:\Annaconda\envs\SAM\lib\site-packages\mmcv\utils\registry.py", line 212, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "C:\Annaconda\envs\SAM\lib\site-packages\mmcv\cnn\builder.py", line 27, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "C:\Annaconda\envs\SAM\lib\site-packages\mmcv\utils\registry.py", line 55, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
TypeError: CLRerNet: __init__() missing 4 required positional arguments: 'code', 'msg', 'hdrs', and 'fp'

Process finished with exit code 1

**Comment by Alexbeast-CN** [comment]
The reason for causing this error is becuase the websit for download dla34-ba72cf86.pth is down.

So, manually download dla34 form: [this site](https://code.ornl.gov/thorn/thorn-model-zoo/-/blob/main/dla34-ba72cf86.pth), and move it to /home/docker/.cache/torch/hub/checkpoints/dla34-ba72cf86.pth will work.

**Comment by hirotomusiker** [comment]
Thank you! We will look at it and change the download url if necessary.

**Comment by hirotomusiker** [comment]
As for Oct.16 2024, the model is downloadable from the default url. So we leave it as it is. Please report again if this issue occurs again.
