### ISSUE TITLE
FileNotFoundError: clrernet_culane_dla34_ema.pth can not be found.

### ISSUE THREAD

**Issue by masyrezaei** [hirotomusiker/CLRerNet#45]
Hi 
Requirement already satisfied: nms in /usr/local/lib/python3.10/dist-packages (0.1.6)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from nms) (1.26.4)
No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
/usr/local/lib/python3.10/dist-packages/mmcv/__init__.py:20: UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components related to the training process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.
  warnings.warn(
load checkpoint from local path: clrernet_culane_dla34_ema.pth
Traceback (most recent call last):
  File "/content/CLRerNet/demo/image_demo.py", line 36, in <module>
    main(args)
  File "/content/CLRerNet/demo/image_demo.py", line 27, in main
    model = init_detector(args.config, args.checkpoint, device=args.device)
  File "/usr/local/lib/python3.10/dist-packages/mmdet/apis/inference.py", line 46, in init_detector
    checkpoint = load_checkpoint(model, checkpoint, map_location='cpu')
  File "/usr/local/lib/python3.10/dist-packages/mmcv/runner/checkpoint.py", line 638, in load_checkpoint
    checkpoint = _load_checkpoint(filename, map_location, logger)
  File "/usr/local/lib/python3.10/dist-packages/mmcv/runner/checkpoint.py", line 572, in _load_checkpoint
    return CheckpointLoader.load_checkpoint(filename, map_location, logger)
  File "/usr/local/lib/python3.10/dist-packages/mmcv/runner/checkpoint.py", line 314, in load_checkpoint
    return checkpoint_loader(filename, map_location)  # type: ignore
  File "/usr/local/lib/python3.10/dist-packages/mmcv/runner/checkpoint.py", line 333, in load_from_local
    raise FileNotFoundError(f'{filename} can not be found.')
FileNotFoundError: clrernet_culane_dla34_ema.pth can not be found.

**Comment by hirotomusiker** [comment]
Please download the file from:
https://github.com/hirotomusiker/CLRerNet/releases/download/v0.1.0/clrernet_culane_dla34_ema.pth
Thanks!
