### ISSUE TITLE
how run demo in Tag CLRerNet-feature-curvelanes  error

### ISSUE THREAD

**Issue by RDXiaoLu** [hirotomusiker/CLRerNet#53]
python demo/image_demo.py demo/demo.jpg configs/clrernet/curvelanes/clrernet_curvelanes_dla34.py  /data/yuanhui/CLRerNet-feature-curvelanes_all/work_dirs/clrernet_curvelanes_dla34/epoch_15.pth --out-file=result2.png
load checkpoint from local path: /data/yuanhui/CLRerNet-feature-curvelanes_all/work_dirs/clrernet_curvelanes_dla34/epoch_15.pth
Traceback (most recent call last):
  File "/data/yuanhui/CLRerNet-feature-curvelanes_all/demo/image_demo.py", line 36, in <module>
    main(args)
  File "/data/yuanhui/CLRerNet-feature-curvelanes_all/demo/image_demo.py", line 29, in main
    src, preds = inference_one_image(model, args.img)
  File "/data/yuanhui/CLRerNet-feature-curvelanes_all/libs/api/inference.py", line 41, in inference_one_image
    data = test_pipeline(data)
  File "/data/yuanhui/CLRerNet-feature-curvelanes_all/libs/datasets/pipelines/compose.py", line 35, in __call__
    data = t(data)
  File "/data/yuanhui/CLRerNet-feature-curvelanes_all/libs/datasets/pipelines/lane_formatting.py", line 484, in __call__
    img_meta[key] = results[key]
KeyError: 'crop_shape'

**Comment by hirotomusiker** [comment]
We haven't prepared image_demo.py for `curvelanes` models, but probably you can fix it by using the following part 

https://github.com/hirotomusiker/CLRerNet/blob/feature/curvelanes/libs/datasets/curvelanes_dataset.py#L87-L120

at this part:

https://github.com/hirotomusiker/CLRerNet/blob/main/libs/api/inference.py#L21-L33

Thank you.
